Feature/pilot dashboard block component
3lvia/kunde-elvia-web pull request #102
Opened 2020-09-18 08:26 UTC by JonatanPaalsson

OMEGA-126

## What is the reason for this change?

Pilot customers should get a dashboardblock with information regarding the new graph and communication strategy

### What is the expected result?

Pilotusers should get a new dashboardblock right below the pilotgraph

## How is it solved?

This is solved with a new PilotDashboard component. I wanted to use a separate component for Pilots in order to easy structure core connected to the pilot. Here we choose the correct terms from contentful depending on your tariffgroup and communication strategy

![image](https://user-images.githubusercontent.com/5526190/93574513-ca252a80-f998-11ea-8c0f-ea25e9a19c87.png)

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] No changes in production
- [ ] Users without pilot should not be shown the new dashboardblock
- [ ] Users with pilot should get a dashboardblock with information connected to your tariffgroup and communication strategy

2020-09-21 06:39 UTC, lobunto requested changes

2020-09-21 06:39 UTC, lobunto commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.tsx
> +  communicationStrategy: number
Should we probably have some types for what numbers these can have, instead of just `number`?

2020-09-21 12:30 UTC, lobunto approved these changes

2020-09-22 06:40 UTC, eTallang commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.module.scss
> +  overflow-wrap: anywhere;
It doesn't look like this is supported in IE11. Whats our strategy/goal for IE support?

2020-09-22 06:41 UTC, eTallang commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.module.scss
> +  overflow-wrap: anywhere;
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

2020-09-22 06:42 UTC, eTallang commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.module.scss
> +  overflow-wrap: anywhere;
Probably not a big deal though, since this is just an initial PR for the new features?

2020-09-22 06:44 UTC, eTallang requested changes

2020-09-22 06:44 UTC, eTallang commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.tsx
> +    <div>
This div can probably be removed

2020-09-22 06:44 UTC, eTallang commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.tsx
> +        <Typography type={TypographyType.TITLE_SMALL}>{title}</Typography>
I think this component can be replaced by the `TitleSmall`-component for better readability.

2020-09-22 06:45 UTC, JonatanPaalsson commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.module.scss
> +  overflow-wrap: anywhere;
Nice catch!
Our strategy is that it should functionally work but we do close to nothing of testing or maintaining. For example the current frontpage dosen't load any images in IE11

2020-09-22 08:41 UTC, eTallang commented on packages/web/src/components/PilotDashboardBlock/PilotDashboardBlock.module.scss
> +  overflow-wrap: anywhere;
So lets keep it then :slightly_smiling_face:

2020-09-22 08:43 UTC, eTallang approved these changes
LGTM

2020-09-22 08:46 UTC, merged