Feature/omega 31 new access overview
3lvia/kunde-elvia-web pull request #107
Opened 2020-09-21 07:49 UTC by ragnhildlarsen

OMEGA-31

## What is the reason for this change?

Accesses to contracts should be shown on a customer relation level, instead of on contract/meterpoint level as it currently is today.

### What is the expected result?

[Figma sketches](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=1%3A33)

## How is it solved?

A new tab with "Tilganger" should be visible on a customer detail page. 

Added a new folder in template for the new view called `AccessOverview`. I used the Table component for web to get the correct structure of the table on mobile. The table should have more columns if it is a private customer relationship, than if it is an organisational/"Bedrift". The column for last logged in date is not supported by the backend yet. 

Because of the new data structure in the backend, I needed to change the structure of how the requests are stored in the state. 

The information box only includes the link to requesting a private customer relationship because requesting access to an organisation customer relation is not supported yet. 

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Access overview looks identical with the design defined in Figma
- [ ] Table shows correct accesses to the customer relationship
- [ ] Roles is displayed correct for private customer relationships
- [ ] Revoke access request is only available for owners

2020-09-21 14:23 UTC, JonatanPaalsson requested changes
There seems to be a lot of functions in `AccessOverview` that try to select specific data from redux. Do you think some of these could be selectors instead?

2020-09-21 14:23 UTC, JonatanPaalsson commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    isCustomerOwnerOfContract = useSelector((state: RootState) =>
Won't this just set `isCustomerOwnerOfContract` for the last contract in the list?

2020-09-21 14:23 UTC, JonatanPaalsson commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    return customerAccessList.findIndex(
Maybe use some instread of findIndex? Something similar to this...
`return customerAcessList.some(customerAccess => customerAccess.id === id)`

2020-09-21 14:23 UTC, JonatanPaalsson commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +  const tableData = [tableHeader]
isn't tableHeader already an array?

2020-09-21 14:23 UTC, JonatanPaalsson commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    tableHeader = [
Can't this just be an array of HTMLElements?

2020-09-23 07:14 UTC, ragnhildlarsen commented on packages/web/src/store/accessRequestSent/accessRequestSent.ts
> +      state.sentRequests[0].accessRequests.push(accessRequest)
sentRequests is the requests sent by the user logged in. Since the new data structure aggregates all requests from a user into one object this should only contain one accessRequestWrapper. I'm not sure that doing this state change is necessary at all, because sentRequests are retrieved from the backend when a user enters minside, so it might be possible to remove it completely.

2020-09-23 07:16 UTC, ragnhildlarsen commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    tableHeader = [
Tried to remove `{ value: }` and just list the `<p>` tags, but the Table component expect it to be at the format that it is now.

2020-09-23 07:17 UTC, ragnhildlarsen commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    isCustomerOwnerOfContract = useSelector((state: RootState) =>
Moved this outside the forEach loop so it should be more correct now.

2020-09-23 08:20 UTC, lobunto requested changes

2020-09-23 08:20 UTC, lobunto commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +      const contractIds = req.accessRequests.map(r => r.contractIds)
`req.accessRequests` seems to be undefined since `accessRequests` is no prop on the requests sent into this function

2020-09-23 12:32 UTC, ragnhildlarsen commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +      const contractIds = req.accessRequests.map(r => r.contractIds)
This is because the backend changes are only in the dev environment so it does not work to test via the netlify link.

2020-09-24 08:41 UTC, lobunto commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +      const contractIds = req.accessRequests.map(r => r.contractIds)
Ok, it seemed to look fine when I tested it yesterday.

2020-09-24 09:20 UTC, lobunto requested changes

2020-09-24 09:20 UTC, lobunto commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    )
Can we have the const keyword before each variable here? It's hard to see what uses selectors and not. All the variables using the `useSelector` could also be moved into a single `useSelector`

Something like this:
```
const {
    requestsSent,
    requestsReceived,
    accessToken,
    contracts,
    ownerId,
    customer,
  } = useSelector((state: RootState) => ({
    customer: customersSelectors.getCustomerById(state, customerId),
    ownerId: customersSelectors.getOwnerId(state),
    contracts: contractsSelectors.getContractsForCustomer(state, customerId),
    accessToken: oidcSelectors.getAccessToken(state),
    requestsSent: accessRequestSentSelectors.getSentRequests(state),
    requestsReceived: accessRequestReceivedSelectors.getReceivedRequests(state),
  }))
```

2020-09-24 09:24 UTC, lobunto commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    tableHeader = [
Probably we can make a function that maps over table elements and wraps them with the `value-object`

2020-09-24 09:27 UTC, lobunto commented on packages/web/src/templates/AccessOverview/AccessOverview.tsx
> +    tableHeader = [
Thinking something like this could work: 
```
const tableHeaders = [terms.personsWithAccessHeader, terms.phoneHeader]
 
const tableValueObjects = tableHeaders.map(term => ({ value: <p>{term}</p> }))

const tableData = [tableValueObjects]
```

2020-09-24 09:40 UTC, JonatanPaalsson commented on packages/web/src/components/Table/Table.tsx
> +  console.log(data)
Ops

2020-09-24 10:58 UTC, JonatanPaalsson approved these changes

2020-09-24 12:47 UTC, lobunto approved these changes

2020-09-24 13:04 UTC, merged