Feature/omega 30 new han port info view
3lvia/kunde-elvia-web pull request #111
Opened 2020-09-21 14:41 UTC by steinmy

OMEGA-30

## What is the reason for this change?

HAN-port page has a new design

### What is the expected result?

HAN-port page should look the same as in the Figma sketches.

https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=1%3A33

## How is it solved?

By changing the layout and styling of the HAN-port page and some related components.

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Look at the han port page in multipe screen sizes
- [ ] Try to use the functionality of the HAN-port page, and see that it works and look correct in multipe screen sizes

2020-09-21 14:53 UTC, steinmy commented on packages/web/src/components/HANPortPhone/HANPortPhone.tsx
> +        fontSize={16 * (16 / 14)}
Is there a prettier way to do this? I found that this was needed in order to get the icon to be 16 px wide due to relative font sizes.

2020-09-21 14:53 UTC, steinmy commented on packages/web/src/components/HANPortList/HANPortList.tsx
> -        <Expandable
The `Expandable` component is now not used anywhere. Should it be deleted?

2020-09-22 06:18 UTC, ragnhildlarsen commented
Have you added any route for this so it can be tested?

2020-09-22 06:34 UTC, marasva commented
https://5f68bce23920b81925704416--elvia-test.netlify.app/minside/hanport/4c9923d4-e83f-48cd-b008-04cb879e8ed9. Here is a link @ragnhildlarsen

2020-09-22 06:51 UTC, marasva commented
![image](https://user-images.githubusercontent.com/23313203/93850860-4bd5ca80-fcaf-11ea-8b3d-3a599c57f896.png)
The HAN-port is supposed to be a part of the tabs? In that case change / add the routes in CustomerDetail.tsx and minside.tsx? Then the "Tilbake til målersiden"-button should also be changed / removed.

2020-09-22 09:14 UTC, marasva commented
![image](https://user-images.githubusercontent.com/23313203/93861089-42089300-fcc0-11ea-9486-734edd83cbb9.png) 

Don't know if it is anything you should do about it, but on mobile (and maybe normal screen on desktop) the warning box shows up on top of the screen, so it is not possible to see what is actually wrong. Maybe it should popup right above the "Bestill åpning" button, so it is possible to see what is actually wrong? 

Or that it is not even possible to tap the button (greyed out) if the requirements are not satisfied. But this last point is probably out of scope for this task?

2020-09-22 09:20 UTC, marasva commented
![image](https://user-images.githubusercontent.com/23313203/93864514-4edbb580-fcc5-11ea-9357-889ab9fd8f2c.png)

The warning icon is not centered. But this should maybe be centered generally and not just for HAN-port?

2020-09-22 09:34 UTC, marasva commented
![image](https://user-images.githubusercontent.com/23313203/93865944-51d7a580-fcc7-11ea-9de8-e9f53935895f.png)
On mobile if you uncheck the checkbox the box is still colored green even though it should be without color. To remove the color you have to actively tap somewhere else on the screen. Can be perceived as a bit misleading.

2020-09-22 11:55 UTC, steinmy commented
> Don't know if it is anything you should do about it, but on mobile (and maybe normal screen on desktop) the warning box shows up on top of the screen, so it is not possible to see what is actually wrong. Maybe it should popup right above the "Bestill åpning" button, so it is possible to see what is actually wrong?
> 
> Or that it is not even possible to tap the button (greyed out) if the requirements are not satisfied. But this last point is probably out of scope for this task?

Nice catch! This should definitely be looked into, but perhaps as another task or at least a separate pull request. I have informed Malin, so we'll see what she says.

2020-09-22 11:57 UTC, steinmy commented
@marasva 
> 
> ![image](https://user-images.githubusercontent.com/23313203/93864514-4edbb580-fcc5-11ea-9357-889ab9fd8f2c.png)
> 
> The warning icon is not centered. But this should maybe be centered generally and not just for HAN-port?

Thanks for the feedback! I have noticed this, and reported it as a bug. It is however also a problem in the old solution, so I don't think it needs to be addressed in this pull request, but rather as a separate task about fixing the warning component in general.

2020-09-22 13:19 UTC, steinmy commented
@marasva 
> The HAN-port is supposed to be a part of the tabs? In that case change / add the routes in CustomerDetail.tsx and minside.tsx? Then the "Tilbake til målersiden"-button should also be changed / removed.

I was going to do this in a separate pull request after this one is done, but I'm looking into it now, and if it turns out to be quickly done I can include it in this one.

2020-09-23 09:21 UTC, ragnhildlarsen commented on packages/web/src/components/HANPortList/HANPortList.tsx
> +      className={classnames(className, css.hanPortList)}
The css class `hanPortList` seems to not exist anywhere. Should it be removed?

2020-09-23 09:23 UTC, ragnhildlarsen commented on packages/web/src/templates/HANPort/HANPort.tsx
> +          {hasClosedStausOrIsEmpty
typo in `hasClosedStausOrIsEmpty`, should probably be `hasClosedStatusOrIsEmpty`

2020-09-23 09:49 UTC, steinmy commented on packages/web/src/components/HANPortList/HANPortList.tsx
> +      className={classnames(className, css.hanPortList)}
Ah, it was removed in a recent refactoring. Thanks for the heads up!

2020-09-23 11:34 UTC, ragnhildlarsen commented on packages/web/src/templates/HANPort/HANPort.tsx
>    const contractList = sortedContractsAndHANEvents.map(
Ensure that the contracts shown are connected to the customer relationship that is selected. E.g. Per Hansen only have 2 contracts related to his customer relationship and Testbedrift 1 has 4 contracts. You could have a look at Erik's PR for meterpoints table to see how he only retrieves the contracts relevant to the customer relationship that is selected.

2020-09-23 11:35 UTC, ragnhildlarsen commented on packages/web/src/templates/HANPort/HANPort.tsx
> +        <div>{terms.asideContentText}</div>
typo in `asideContentText`?

2020-09-23 11:37 UTC, ragnhildlarsen requested changes
Had a few comments but overall it looks really good! :)

2020-09-23 11:51 UTC, steinmy commented on packages/web/src/templates/HANPort/HANPort.tsx
> +        <div>{terms.asideContentText}</div>
resolved after discussion, not a typo

2020-09-25 12:55 UTC, steinmy commented on packages/web/src/components/HANPortPhone/HANPortPhone.tsx
> +        fontSize={16 * (16 / 14)}
Fixed

2020-09-25 13:10 UTC, steinmy commented on packages/web/src/templates/HANPort/HANPort.tsx
>    const contractList = sortedContractsAndHANEvents.map(
Postponed to next PR after discussion

2020-09-26 12:55 UTC, ragnhildlarsen commented
Two comments on mobile view:
- Text next to edit icon should be left aligned aligned according to the sketches: https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=10172%3A921
- it also looks like the text should be "Rediger"?
- Looks like the checkbox should be aligned at the top with the text next to it? 

<img width="375" alt="Screenshot 2020-09-26 at 14 47 27" src="https://user-images.githubusercontent.com/50363113/94341191-cbdd9680-0007-11eb-9f01-02a0b5919431.png">

2020-09-26 13:01 UTC, ragnhildlarsen commented on packages/web/src/components/HANPortList/HANPortList.tsx
> +import classnames from 'classnames'
classnames import is unused

2020-09-26 13:10 UTC, ragnhildlarsen commented on packages/web/src/components/HANPortPhone/HANPortPhone.tsx
> +          </TextDescription>
Why is the first term wrapped in `<></>` and not the second one after `:`?

2020-09-26 13:14 UTC, ragnhildlarsen commented on packages/web/src/templates/HANPort/HANPort.module.scss
> +  font-size: 24px;
emCalc?

2020-09-26 13:14 UTC, ragnhildlarsen commented on packages/web/src/templates/HANPort/HANPort.module.scss
> +    font-size: 20px;
emCalc?

2020-09-26 13:14 UTC, ragnhildlarsen commented on packages/web/src/templates/HANPort/HANPort.module.scss
> +      font-size: 20px;
emCalc?

2020-09-26 13:14 UTC, ragnhildlarsen commented on packages/web/src/templates/HANPort/HANPort.module.scss
> +        font-size: 18px;
emCalc?

2020-09-28 08:48 UTC, steinmy commented
@ragnhildlarsen 
> 
>     * it also looks like the text should be "Rediger"?
> 

This is controlled in Contentful, and I will change the text when the code is in production

2020-09-28 09:13 UTC, steinmy commented on packages/web/src/components/HANPortPhone/HANPortPhone.tsx
> +          </TextDescription>
Nice catch! This is a leftover from the old code and can be deleted.

2020-09-28 10:44 UTC, t0ff3r commented
@steinmy whats the status here? Is it ready for a re-review from @ragnhildlarsen ?

2020-09-28 10:45 UTC, steinmy commented
> 
> 
> @steinmy whats the status here? Is it ready for a re-review from @ragnhildlarsen ?

Yes, she's on it :)

2020-09-28 11:11 UTC, ragnhildlarsen approved these changes

2020-09-28 11:38 UTC, eTallang commented
I guess that the HAN-port tab is introduced in another task?

2020-09-28 11:41 UTC, merged