feat(web): add history label in MeteringPointRow
3lvia/kunde-elvia-web pull request #122
Opened 2020-09-25 09:26 UTC by lobunto

OMEGA-221

## What is the reason for this change?

Add history label for contracts with an `endTime` 

### What is the expected result?
In the metering point list, contracts with an `endTime` should get an "Historisk måler" label displayed instead of monthly consumption.

![Screenshot 2020-09-25 at 11 22 58](https://user-images.githubusercontent.com/6702553/94250401-7929af00-ff21-11ea-9997-4e76c3eb0ca4.png)

## How is it solved?

Checks if a contract has `endTime` not `null`

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |       |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] The "Historisk måler" label is visible for contracts with `endTime`
- [ ] The current monthly consumption (or "-") is visible for contracts without `endTime`

2020-09-25 13:55 UTC, eTallang requested changes

2020-09-25 13:55 UTC, eTallang commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +    always(<Label data-testid="Label">Historisk måler</Label>),
What's the purpose of the `data-testid`-attribute?

2020-09-25 13:55 UTC, eTallang commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +  const hasEndTime = complement(propEq('endTime', null))
I'm not sure what benefits rambda provides here over a regular `if/else`-expression

2020-10-01 16:00 UTC, steinmy submitted a review, later dismissed

2020-10-01 16:00 UTC, steinmy commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +  const isHistory = ifElse(
The `isHistory` variable serves two purposes: indicating whether the meterpoint is expired, and containing the label. How about instead building a `consumptionFieldContent` which is set to either the label or `getCurrentMonthsConsumption()` depending on whether `hasEndTime` is true or false?

2020-10-05 06:24 UTC, lobunto commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +    always(<Label data-testid="Label">Historisk måler</Label>),
`data-testid` is supposed to make it easier for selecting stuff when testing, it is not special for React in any way. But I actually will remove it here since it is already added to the Label component in `ui`

2020-10-05 07:38 UTC, eTallang requested changes

2020-10-05 07:38 UTC, eTallang commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +import { always, complement, ifElse, propEq } from 'ramda'
I believe these are unused now

2020-10-05 07:39 UTC, lobunto commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +import { always, complement, ifElse, propEq } from 'ramda'
yep, fixed :)

2020-10-05 07:42 UTC, eTallang approved these changes
LGTM

2020-10-05 09:20 UTC, t0ff3r commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +
As `getCurrentConsumption` already returns a string I don`t see why that function should not handle returning '-' aswell?

2020-10-05 09:25 UTC, lobunto commented on packages/web/src/templates/Meterpoints/MeteringPointRow.tsx
> +
Sure, just pushed a commit with fixes. Take a look at it @t0ff3r

2020-10-05 10:33 UTC, merged