Chore/omega 100 clean up routing
3lvia/kunde-elvia-web pull request #125
Opened 2020-09-25 13:14 UTC by eTallang

OMEGA-100

## What is the reason for this change?

Previously, routing on min side was done through a combination of entries in `basePaths.json` and hard coded strings.

### What is the expected result?

This change removes all hard coded strings and introduces a single source for all routes.

## How is it solved?

A new file `routing.ts` is introduced that contains all routes and a few utility functions to create and manipulate urls.

2020-09-25 14:49 UTC, steinmy requested changes

2020-09-25 14:49 UTC, steinmy commented on packages/web/src/routing.ts
> +    if (url === routes.meteringPoint);
What is happening here? It seems like this line does nothing, or perhaps I'm misunderstanding?

2020-09-28 06:33 UTC, t0ff3r commented on packages/web/src/routing.ts
> +    if (url === routes.meteringPoint);
I agree

2020-09-28 06:41 UTC, t0ff3r approved these changes
Think this looks great! Maybe remove that if doing nothing and consider if /faktura should be /fakturaer for consistency in single/plural. Other than that I'd say ship it :-)

2020-09-28 06:42 UTC, t0ff3r commented on packages/web/src/routing.ts
> +  invoices: `/minside/:${customerIdToken}/faktura/:${contractIdToken}`,
/faktura could maybe be fakturaer since we use tilganger/malere

2020-09-28 07:41 UTC, eTallang commented on packages/web/src/routing.ts
> +    if (url === routes.meteringPoint);
Good catch. Strange that it ended up in the PR. Removed.

2020-09-28 07:58 UTC, marasva commented
If I try to log in with Randi Rystad or Ali Jensen in test and my own account in prod I get this error message: 
`Error: Number of provided params to getUrlWithParams does not match with required url params.`

2020-09-28 08:53 UTC, marasva commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +      navigate(getUrlWithParams(routes.myPage, customerIds[0]))
In relation to my previous comment it worked for me by just changing routes.myPage to routes.customerPage here.

2020-09-28 09:12 UTC, eTallang commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +      navigate(getUrlWithParams(routes.myPage, customerIds[0]))
A very good catch.

2020-09-28 13:45 UTC, merged