Feature/OMEGA-220 Add metering point description to metering points table
3lvia/kunde-elvia-web pull request #128
Opened 2020-09-28 09:14 UTC by ragnhildlarsen

OMEGA-220

## What is the reason for this change?

Metering points table should have a column for metering point description according to the [Figma sketches](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=9560%3A55962 - Connect to preview)

### What is the expected result?

Metering point description should be shown if the metering point description has a value, otherwise it should show `-`

<img width="1358" alt="Screenshot 2020-09-28 at 11 06 50" src="https://user-images.githubusercontent.com/50363113/94412955-b9d03500-017a-11eb-9cc6-6607ee5e6f50.png">

## How is it solved?

Solved by adding a new term in Contentful for "Målerbeskrivelse" that was used by a new `<th>` tag. In the MeteringPointRow a new `<td>` tag was added that accessed the metering point description value. 

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Metering point description should be shown in the table
- [ ] If the metering point description value is null, `-` should be shown

2020-09-28 09:16 UTC, ragnhildlarsen commented
Had to merge PR for OMEGA-146 to include some changes related to using terms in the table.

2020-09-28 09:43 UTC, eTallang commented
You probably want to convert this to a draft, since it depends on the filter task being merged :slightly_smiling_face:

2020-09-28 11:03 UTC, t0ff3r approved these changes

2020-09-28 11:04 UTC, t0ff3r commented
Does the description exist for any meters yet? Or is this column empty for everyone?

2020-09-28 11:06 UTC, eTallang requested changes

2020-09-28 11:06 UTC, eTallang commented on packages/web/src/services/customer-portal-api.ts
> +  meteringPointDescription: string
A description is probably optional (should be confirmed)? Should in that case be marked with `?`.

2020-09-28 11:13 UTC, ragnhildlarsen commented
> Does the description exist for any meters yet? Or is this column empty for everyone?

I guess some meters may have a description but the only way to set a description is to contact customer service so probably not many meters that have it.

2020-09-28 11:18 UTC, ragnhildlarsen commented on packages/web/src/services/customer-portal-api.ts
> +  meteringPointDescription: string
When testing the endpoint in swagger it seems like it always returns contracts with metering points that have the field meteringPointDescription. The value is null if description is not set.

2020-09-28 12:08 UTC, eTallang commented on packages/web/src/services/customer-portal-api.ts
> +  meteringPointDescription: string
Maybe we could set the type to `string | null` in that case then :slightly_smiling_face:

2020-09-29 08:26 UTC, t0ff3r approved these changes

2020-09-29 10:16 UTC, eTallang approved these changes
LGTM

2020-09-30 06:47 UTC, merged