add cypress as new package
3lvia/kunde-elvia-web pull request #130
Opened 2020-09-28 13:47 UTC by JonatanPaalsson

OMEGA-211

## What is the reason for this change?

To make the project a bit more stable and to remove manual testing on the website, we have decided to implement some automated tests. For this Cypress was the framework that we have decided to use. 

### What is the expected result?

Any developer should now be able to run cypress locally.

## How is it solved?

By adding cypress as a new package

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Run `yarn cypress:open` while having a local version of the project running
- [ ] Run and verify all new tests

2020-09-29 07:19 UTC, eTallang requested changes

2020-09-29 07:19 UTC, eTallang commented on packages/cypress/cypress/integration/frontpage/shortcuts.spec.ts
> +    cy.get('.SectionShortcuts-module--shortcut--1bsiR').each(($el, index) => {
We should probably use `[data-cy]`-selectors instead of class selectors (referencing the [Best Practices](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements). Should we in that case introduce some general rule for adding `[data-cy]`-attributes in the HTML upfront, or should it be added when writing the Cypress tests?

2020-09-29 07:19 UTC, eTallang commented on packages/cypress/cypress/plugins/index.ts
> +/// <reference types="cypress" />
Can this file be removed?

2020-09-29 07:19 UTC, eTallang commented on packages/web/src/components/Search/SearchField.tsx
>          data-testid="search-input"
What are the `data-testid`-attributes for?

2020-09-29 08:43 UTC, JonatanPaalsson commented on packages/cypress/cypress/integration/frontpage/search.spec.ts
> +    cy.wait(500)
Yes, the thing is that our website is not intractable for some time once it has loaded. So even if it finds the element in the DOM, it might not be able to click on it. When removing the wait the test fails about 50% of the time 🤷

2020-09-29 08:58 UTC, JonatanPaalsson commented on packages/cypress/cypress/plugins/index.ts
> +/// <reference types="cypress" />
It can. Same for `commands` and `fixtures`. These are some files that were provided on install that i decided to keep in order to keep the suggested folder-structure and to show some potential features of cypress. What do you think?

2020-09-29 08:59 UTC, JonatanPaalsson commented on packages/web/src/components/Search/SearchField.tsx
>          data-testid="search-input"
Not sure actually, might be for old puppeteer tests or some tracking 🤷

2020-09-29 10:25 UTC, eTallang commented on packages/cypress/cypress/plugins/index.ts
> +/// <reference types="cypress" />
We had great use of the `commands` at my previous project. Commands are really useful to create custom commands that is added to the global `cy`-object. For example, we added a `login`-method that allowed us to do the following:
```
cy.login('admin@trim.com').<additional chainable calls>
```

Another good example was the `goToPage`-method:
```
cy.goToPage('Customers').get('[data-cy]="title"')...
```
It's a really handy way of adding general-purpose actions that is likely to be repeated in many tests, while it also ensures that  the next step is not performed before the previous is finished.

I'm pretty sure we'll get some commands in this project sooner or later, so I vote for keeping the `commands` at least :smiley:

2020-09-29 10:26 UTC, eTallang commented on packages/web/src/components/Search/SearchField.tsx
>          data-testid="search-input"
I see them all around, while I'm pretty sure we don't have tests that use them. It's not related to this PR though, but I suggest that we have a chat about them in the team, and decide whether to keep them and use them, or remove them.

2020-09-29 10:34 UTC, eTallang commented on packages/cypress/cypress/integration/frontpage/search.spec.ts
> +    cy.wait(500)
Hmm that's weird. I feel like we should try to solve this Cypress-challenge now, before we start writing lots of tests. I have bad experience with introducing `wait`s in tests, where the tests in that project after a while took over 40 mins to run, since the tests had `wait`s all over.

2020-09-30 11:58 UTC, JonatanPaalsson commented on packages/cypress/cypress/integration/frontpage/search.spec.ts
> +    cy.wait(500)
Definitely agree. I removed most of the waits, but I can't remove this one at this time. Our current header is rerendering 2 times on desktop because of the `useMedia`-hook used in the header. This hook assumes that the device is on a mobile (since most of our users are on mobile), and this causes a rerender when we "switch" to desktop.

So what happens in the test is that cypress finds the element and tries to click it. But if there is a rerender between these two operations, then the test fails. Resolving the rerender issue would be to rewrite a lot in the header which I don't want to do in this pr, so therefor I keept the wait. If you have any other ideas how this could be solved, I'd love to hear it :)

2020-09-30 13:04 UTC, eTallang approved these changes
LGTM

2020-09-30 13:26 UTC, FredricW commented on packages/web/src/components/Search/SearchField.tsx
>          data-testid="search-input"
They exists for unit testing.

2020-10-01 08:26 UTC, t0ff3r approved these changes

2020-10-01 08:41 UTC, merged