Feature/omega 147 redirect to metering page
3lvia/kunde-elvia-web pull request #133
Opened 2020-09-29 09:28 UTC by marasva

[OMEGA-147](https://elvia.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=OMEGA&modal=detail&selectedIssue=OMEGA-147)

## What is the reason for this change?

For private customers who mainly have only one meterpoint it is confusing to get it in a table first. Therefore customers with only one meterpoint is redirected straight to the meterpoint site. 

### What is the expected result?

![image](https://user-images.githubusercontent.com/23313203/94539537-a2aa4980-0245-11eb-8872-2efd82de1e6d.png)

## How is it solved?

Change CustomerRelationOverview to redirect only if the customer have one customerRelations and one contract (Randi Rystad). Also added changes to CustomerCard if the customer has several customerRelations but only one meterpoint on each card the customer should be redirected to the meterpoint page straight away (Per Hansen's access to Randi Rystad). Also had to add changes to how the tabs behave since they do not get rerouted to the correct address since the hierarchy is a bit changed when some customers are skipping a link. Also needed to change a bit so the breadcrumbs behave correctly.

Have used the new implementation of tabs, so it is set as draft until the tabs are in production. 

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |         |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Check that is has the expected behavior for all the test users (Randi Rystad, Ali Jensen, Per Hansen)
- [ ] Check that is has the expected behavior for your own user in prod
- [ ] Check breadcrumbs

2020-09-30 13:40 UTC, steinmy requested changes
Looks good to me, but I found some refactoring opportunities

2020-10-01 06:29 UTC, steinmy requested changes
Some more refactoring suggestions

2020-10-01 06:29 UTC, steinmy commented on packages/web/src/components/CustomerCard/CustomerCard.tsx
> +      : null
```suggestion
  const customerContracts = contracts?.filter(c => c.customerId === customer.id)
```
Here the optional chaining operator `?.` can be used to achieve the same effect more conciesly

2020-10-01 06:29 UTC, steinmy commented on packages/web/src/components/CustomerCard/CustomerCard.tsx
> +      : false
```suggestion
  const onlyHaveOneContract = customerContracts?.length === 1
```

2020-10-01 06:29 UTC, steinmy commented on packages/web/src/components/CustomerCard/CustomerCard.tsx
> +      : null
```suggestion
  const contractId =
    onlyHaveOneContract 
      ? customerContracts[0]?.id
      : null
```

2020-10-01 06:29 UTC, steinmy commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +      if (meteringPointPageMatch && !onlyHaveOneContract) {
I know this has nothing to do with your changes, but while trying to understand the code, it took a while for me to realize what `meteringPointPageMatch` means. If I'm not wrong, it indicates whether the current page shown is the metering point page. Could it perhaps be renamed `currentPageIsMeteringPointPage`. In the same vein, maybe `onlyHaveOneContract` could be renamed `customerOnlyHasOneContract`. Then this line would read "If current page is metering point page and not customer only has one contract" which would explain quite clearly in close to natural language what is actually happening.

2020-10-02 06:51 UTC, t0ff3r requested changes

2020-10-02 06:51 UTC, t0ff3r commented on packages/ui/src/components/Tabs/Tabs.tsx
> +                  : uri + '/' + tab.url
Didn't @eTallang create a helper for creating urls?

2020-10-02 06:51 UTC, t0ff3r commented on packages/ui/src/components/Tabs/Tabs.tsx
> +                  : tab.name}
Tab names should be controlled by the cms

2020-10-02 06:51 UTC, t0ff3r commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +        : navigate(getUrlWithParams(routes.customerPage, customerIds[0]))
I think probably the router should handle what page you end up on, and not be nested navigations in children components. We should discuss this with @eTallang

2020-10-02 06:51 UTC, t0ff3r commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +                contracts={contracts}
Maybe CustomerCard needs to select this data from the store instead of having it passed down everywhere?

2020-10-02 06:57 UTC, marasva commented on packages/ui/src/components/Tabs/Tabs.tsx
> +                  : tab.name}
Yes, have talked with Steinar about that.

2020-10-02 11:28 UTC, marasva commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +                contracts={contracts}
Customer is passed down from before, but removed the contracts being passed down. Should the customer also be removed?

2020-10-05 07:44 UTC, t0ff3r approved these changes

2020-10-05 10:22 UTC, merged