ci: builds contentful extensions with CI and deploys to Netlify
3lvia/kunde-elvia-web pull request #157
Opened 2020-10-07 10:32 UTC by t0ff3r

## What is the reason for this change?

Contentful extensions needs package upgrades to improve security and also we need to build and deploy it to netlify due to size restrictions on contentful hosted extensions

### What is the expected result?

Less security notifications and easier maintainance of extensions from now on

## How is it solved?

Adds a new pipeline config for extensions and deploys to two new pages in netlify.

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Verify that table still works in contentful test by making a table, publish and verify
- [ ] Verify that use-form-fields still works in contentful test by making a form, publish and verify

2020-10-08 12:20 UTC, erlbe commented on CI/azure-pipeline.extensions.yml
> +    - extensions/*
Since we are using branch-naming conventions to trigger different pipelines. Maybe they should be documented in the readme file? Like `extensions/*` and `migrations/*`

2020-10-08 12:46 UTC, t0ff3r commented on CI/azure-pipeline.extensions.yml
> +    - extensions/*
This is path triggers, not branch naming :-) Only care about triggering the build if a changed happened in this folder.

2020-10-08 12:50 UTC, erlbe commented on CI/azure-pipeline.extensions.yml
> +    - extensions/*
Ah, yes! Never mind then 😄

2020-10-08 13:04 UTC, erlbe approved these changes

2020-10-08 13:39 UTC, JonatanPaalsson requested changes

2020-10-08 13:39 UTC, JonatanPaalsson commented on CI/azure-pipeline.extensions.yml
> +          - script: 'node scripts/netlify.js deploy -s $(siteId) -a $NETLIFY_TOKEN -d build -m "#$(Build.BuildId) - $(Build.SourceBranchName)" --prod'
In the regular pipeline we use `$(prodFlag)`, should we use the same here? Not really sure about the difference 🤷

2020-10-08 18:10 UTC, t0ff3r commented on CI/azure-pipeline.extensions.yml
> +          - script: 'node scripts/netlify.js deploy -s $(siteId) -a $NETLIFY_TOKEN -d build -m "#$(Build.BuildId) - $(Build.SourceBranchName)" --prod'
We add --prod on all builds here as it would not make sense to have deploy previews for this since we do not have lots of environments in contentful.

2020-10-09 05:52 UTC, t0ff3r commented on CI/azure-pipeline.extensions.yml
> +              cd extensions/table
Thanks! Fixed :-)

2020-10-09 06:44 UTC, JonatanPaalsson approved these changes
Nice work!

2020-10-09 07:09 UTC, merged