Feature/video in top banner
3lvia/kunde-elvia-web pull request #17
Opened 2020-09-02 07:24 UTC by corneliusgdahling

OMEGA-53

## What is the reason for this change?
Add support for video in top of page

### What is the expected result?
Play video in featured, with play pause button on hover/focus

![image](https://user-images.githubusercontent.com/10927589/91944062-c8533a00-ecfd-11ea-9b27-76cf81c32777.png)

## How is it solved?
- Created a video component
- Added Video component to featured

## Any changes/updates that may affect others?
|                                     |Changed|
|-------------------------------------|-------|
| Unit tests                          |   x   |
| Dependencies                        |       |
| Environment variables               |       |
| Build scripts                       |       |

## How can it be tested and verified?

Add video to an article, category or maincategory and see if it plays

2020-09-03 11:51 UTC, t0ff3r requested changes
Looks like the height of the video is wrong on desktop? Image we have today is much higher

2020-09-03 11:53 UTC, t0ff3r commented on packages/hdd-icons/index.d.ts
> +export const HddPlayFilledColor: (attr?: {[name: string]: string}) => JSX.Element;
Should these icons not be in elvis instead?

2020-09-03 12:00 UTC, corneliusgdahling commented on packages/hdd-icons/index.d.ts
> +export const HddPlayFilledColor: (attr?: {[name: string]: string}) => JSX.Element;
Maybe. I got sent them directly, so I didn't think so, but can double check.

2020-09-03 12:07 UTC, corneliusgdahling commented
> Looks like the height of the video is wrong on desktop? Image we have today is much higher

You are correct. Fixed

2020-09-03 12:29 UTC, corneliusgdahling commented on packages/hdd-icons/index.d.ts
> +export const HddPlayFilledColor: (attr?: {[name: string]: string}) => JSX.Element;
You are correct. Elvis is on it!

2020-09-04 11:06 UTC, t0ff3r requested changes

2020-09-04 11:06 UTC, t0ff3r commented on packages/web/src/components/Video/Video.tsx
> +  const hideOverlay = () => setshowOverlay(false)
Are these helpers really necessary? I think `setTooltipVisible(false)` is clear enough. Also `setshowOverlay` should probably have a large S.

2020-09-04 11:06 UTC, t0ff3r commented on packages/web/src/templates/Category/Category.tsx
> +          )
Should not the Featured component determine what to show itself?

2020-09-07 06:34 UTC, t0ff3r commented on packages/web/src/components/Video/Video.tsx
> +      onMouseEnter={() => setShowOverlay(true)}
`pipe(T, setShowOverlay)` 😂

2020-09-07 06:46 UTC, t0ff3r commented on packages/web/src/templates/Article/Article.tsx
> +              <Image {...image?.imgProps} focalPoint={image?.focalPoint} />
I guess the optional chaining operator is not needed here since you already do image &&? Doesn`t hurt ofc.

2020-09-07 06:48 UTC, t0ff3r commented
Need to test a final build of this, but looks great :-)

2020-09-07 06:56 UTC, corneliusgdahling commented on packages/web/src/components/Video/Video.tsx
> +      onMouseEnter={() => setShowOverlay(true)}
That is perfect!

2020-09-07 09:56 UTC, t0ff3r commented
Theres something weird going on with the play button when pausing. Try pausing, then unfocusing the button by clicking outside the banner end then try starting it again. First it gets cut in 1/4 and then invisible

2020-09-07 15:03 UTC, t0ff3r commented
Also looks like there is no image in top banner in production build

2020-09-08 07:47 UTC, corneliusgdahling commented
> Theres something weird going on with the play button when pausing. Try pausing, then unfocusing the button by clicking outside the banner end then try starting it again. First it gets cut in 1/4 and then invisible

Fixed

2020-09-08 07:47 UTC, corneliusgdahling commented
> Also looks like there is no image in top banner in production build

Fixed

2020-09-08 11:24 UTC, t0ff3r commented
Video banner with text on mobile needs to be fixed

2020-09-10 12:15 UTC, corneliusgdahling commented
> Video banner with text on mobile needs to be fixed

Fixed. If no mobile video src, it will show `<Image...` on mobile

2020-09-14 09:29 UTC, t0ff3r commented
Is this one ready now? Did you implement it so that video for mobile shows if a source is added?

2020-09-17 06:33 UTC, lobunto commented
@corneliusgdahling what is the status for this PR? There are also some conflicts that should be fixed.

2020-09-23 07:13 UTC, t0ff3r approved these changes

2020-09-23 07:13 UTC, merged