Feat/omega 34 user settings menu
3lvia/kunde-elvia-web pull request #2
Opened 2020-08-31 14:10 UTC by eTallang

OMEGA-34

## What is the reason for this change?
To move the links found on the "Min profil" to the user menu in the top right. This is a part of the redesign of "Min side".

### What is the expected result?
That the new user menu looks like the designs in [Figma](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=10104%3A63803).

## Any changes/updates that may affect others?
|                                     |Changed|
|-------------------------------------|-------|
| Unit tests                          |      |
| Dependencies                        |       |
| Environment variables               |       |
| Build scripts                       |       |

## How can it be tested and verified?

- [ ] Titles are using header tags.
- [ ] Titles looks identical with the typography defined in Figma.
- [ ] Titles in `/min-side` should not be affected and continue to look like this: [screenshot]
- [ ] Unit tests named `typography/titles`

2020-08-31 14:16 UTC, eTallang commented on docs/pull_request_template.md
> +
I'm really not sure why this became a part of the PR. I've never changed this, and I'm not even allowed to commit a revert :confused:

2020-09-01 11:05 UTC, FredricW requested changes
I understand that some of the code is just moved, but it would be nice if you can tidy up the sass a bit! Also some comments on the typography, otherwise looking good.

2020-09-01 11:05 UTC, FredricW commented on packages/web/src/components/HeaderUserMenu/HeaderUserMenu.module.scss
> +  margin-bottom: 2.5rem;
```suggestion
  margin-bottom: spaceCalc(2.5);
```

2020-09-01 11:05 UTC, FredricW commented on packages/web/src/components/HeaderUserMenu/HeaderUserMenu.module.scss
> +  margin-left: 8px;
spaceCalc
```suggestion
  margin-left: spaceCalc(1);
```

2020-09-01 11:05 UTC, FredricW commented on packages/web/src/components/HeaderUserMenu/HeaderUserMenu.module.scss
> +  min-width: 270px;
Use spaceCalc and emCalc instead of setting px values directly 8)

2020-09-01 11:14 UTC, lobunto commented on packages/web/src/components/HeaderUserMenu/HeaderUserMenu.module.scss
> +  margin-bottom: 2.5rem;
Isn't `spaceCalc(5)` more correct here @FredricW?

2020-09-01 11:35 UTC, OysteinThuen commented
Build #3068 successfully built and deployed.

- Prod: https://5f4e311a529e1ad2d784b3f1--elvia-prod.netlify.app
- Test: https://5f4e314067e48bc899784338--elvia-test.netlify.app

2020-09-01 13:49 UTC, FredricW commented
Does it make sense that "Logg ut fra andre enheter" is placed in "Inlogging" and not in "Logg ut" ?

2020-09-02 06:33 UTC, eTallang commented
> Does it make sense that "Logg ut fra andre enheter" is placed in "Inlogging" and not in "Logg ut" ?

Checking with Malin.

2020-09-02 10:15 UTC, eTallang commented
> Does it make sense that "Logg ut fra andre enheter" is placed in "Inlogging" and not in "Logg ut" ?

@FredricW We agreed with your suggestion, so the link has been moved. Ready for another review.

2020-09-02 10:56 UTC, lobunto requested changes

2020-09-02 10:56 UTC, lobunto commented on packages/web/src/components/HeaderUserMenu/HeaderUserMenu.tsx
> +        </a>
Links related to customer relationship will probably not link to Elvid but be relative to mypage. `createHidUrl` should not create links for customer relationships

2020-09-02 10:57 UTC, lobunto requested changes

2020-09-02 10:57 UTC, lobunto commented on packages/web/src/components/HeaderUserMenu/HeaderUserMenu.tsx
> +      ))}
Links related to customer relationship will probably not link to Elvid but be relative to mypage. `createHidUrl` should not create links for customer relationships

2020-09-02 11:12 UTC, lobunto commented on packages/web/src/components/HeaderUserMenu/HeaderUserMenu.tsx
> +  const createHidUrl = (pathToHid: string) =>
*Hid* should also probably be renamed to *Elvid*

2020-09-02 11:20 UTC, lobunto commented
I cannot tell why, but it seems that an illustration is gone from this PR..? In production it looks fine.

![Screenshot 2020-09-02 at 13 19 26](https://user-images.githubusercontent.com/6702553/91974958-eed59d00-ed1e-11ea-8b55-82c54039c4d1.png)

2020-09-02 14:00 UTC, eTallang commented
@lobunto Problem solved. Ready for new review

2020-09-03 06:03 UTC, lobunto commented
> @lobunto Problem solved. Ready for new review

Great, it looks really good :) I've got one more issue. When the link "Be om tilgang" in the menu is clicked the menu doesn't hide. And in some cases, it just quickly hides before it becomes visible again.

2020-09-03 09:11 UTC, FredricW approved these changes
Once Marius' comment is addressed I think it is good to go

2020-09-03 09:56 UTC, eTallang commented
> > @lobunto Problem solved. Ready for new review
> 
> Great @eTallang , it looks really good :) I've got one more issue. When the link "Be om tilgang" in the menu is clicked the menu doesn't hide. And in some cases, it just quickly hides before it becomes visible again.

Fixed :+1:

2020-09-03 10:08 UTC, lobunto approved these changes

2020-09-03 10:25 UTC, merged