refactor/OMEGA 29 add customer information page
3lvia/kunde-elvia-web pull request #22
Opened 2020-09-03 12:04 UTC by marasva

[OMEGA 29](https://elvia.atlassian.net/browse/omega-29)

## What is the reason for this change?

Customer information needed refactoring, a bit of restyling and showing more information.

### What is the expected result?

Customers should see a box with their main information. The component is going to be a part of the refactoring of the header and the menu. 

[Figma sketches](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=9560%3A57683)

## How is it solved?

A new template is created for CustomerInfo. The component gets the information from the customer store. Some styling in the Table module is removed since the content did not longer align properly. In addition some extra functions are added in the utils pack in order to map country code to country name, and to remove excessive information in the CustomerInfo template.  

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] enter /minside/customerinfo in the url to navigate to the page
- [ ] The styling and UI looks identical with the typography defined in Figma.
- [ ] Unit tests for getting phoneNumber and CountryName in 'getCustomerInfo.test'

2020-09-03 15:53 UTC, JonatanPaalsson requested changes

2020-09-03 15:53 UTC, JonatanPaalsson commented on packages/web/src/utils/getCountryName/getCountryName.tsx
> +export function getCountryName(countryCode: string) {
Love the comment! Once approach that I like to do is just name this function based on the comment. So instead of `getCountryName` you can name it `getCountryNameFromCountryCode`. This is just preference tho 😄

2020-09-03 15:53 UTC, JonatanPaalsson commented on packages/hdd-react/src/components/QuoteBlock/QuoteBlock.module.scss
> +  margin: 48px auto;
use spaceCalc instead of px values

2020-09-03 15:53 UTC, JonatanPaalsson commented on packages/hdd-react/src/components/QuoteBlock/QuoteBlock.module.scss
> +    margin: 32px auto;
use spaceCalc instead of px values

2020-09-03 15:53 UTC, JonatanPaalsson commented on packages/web/src/templates/CustomerInfo/CustomerInfo.tsx
> +        {customer && (
You check here if customer exists, if it doesn't exist what happens when you are creating the tableData array?

2020-09-03 15:53 UTC, JonatanPaalsson commented on packages/web/src/utils/getCountryName/getCountryName.tsx
> +      return country[countryCode]
Maybe a test or two would be nice for this function? What happens if I send in "Hello" for example?

2020-09-04 07:53 UTC, steinmy commented on packages/web/src/utils/getCountryName/countryCodes.json
> +  { "CH": "Svets" },
These aren't quite right. I haven't checked all of them, but it might be worth looking into finding a better dataset.

2020-09-04 08:11 UTC, marasva commented on packages/web/src/utils/getCountryName/countryCodes.json
> +  { "CH": "Svets" },
It is scraped so there does not exist a dataset from before. I will look into them again.

2020-09-04 08:32 UTC, marasva commented on packages/hdd-react/src/components/Table/Table.module.scss
>          font-weight: 700;
The font weight is set to 700 to make the first instance of the tables bold. Earlier they were just set on mobile version, but from Figma they are supposed to be set for all sizes. 
![Capture2](https://user-images.githubusercontent.com/23313203/92218754-e05fc080-ee99-11ea-93f4-3ddee131d1ae.PNG)

2020-09-04 09:01 UTC, marasva commented on packages/web/src/templates/CustomerInfo/CustomerInfo.tsx
> +        {customer && (
I just copied this section from the Profile component. But added a check when creating the table.

2020-09-04 11:54 UTC, marasva commented
Had to duplicate the norwegianCustomer into a new constant in getCustomerInfo.test in order to get the getCountryName test to run. Do not know why it did not work just using norwegianCustomer so grateful for any input.

2020-09-07 10:34 UTC, JonatanPaalsson requested changes

2020-09-07 10:34 UTC, JonatanPaalsson commented on packages/web/src/utils/getCustomerInfo/getCustomerInfo.tsx
> +export function getMobilePhone(customer: Customer) {
Arrowfunction would be nice

2020-09-07 10:34 UTC, JonatanPaalsson commented on packages/web/src/utils/getCustomerInfo/getCustomerInfo.tsx
> +export function getCountry(customer: Customer) {
arrowfunction here aswell :)

2020-09-07 10:34 UTC, JonatanPaalsson commented on packages/web/src/utils/getCountryNameFromCountryCode/getCountryNameFromCountryCode.tsx
> +      return country[countryCode]
Should't this return just the countryName and not an object?

2020-09-07 12:07 UTC, marasva commented on packages/web/src/utils/getCountryNameFromCountryCode/getCountryNameFromCountryCode.tsx
> +  if (countryCode.length === 2 && countryCode === countryCode.toUpperCase()) {
Because I made the input be uppercase in the getCountry function, so had to add it here in order for the tests to work. But can change it to just put it in uppercase here instead.

2020-09-07 13:15 UTC, marasva commented on packages/web/src/templates/CustomerInfo/CustomerInfo.tsx
> +  let tableData: any[] = []
If I make the tabledata a const it complains that you cannot assign anything to it because it's a constant. 

I am not entirely sure what you mean? Check whether customer exists or is undefined and then just return <> </>? Which makes the entire page just empty if the customer equals to undefined, or do you mean something else?

2020-09-16 13:53 UTC, marasva commented
Realized after testing with my personal account in prod that I do not have customer information since I am not the owner of the contract. So "my profile" is empty for me. 
![image](https://user-images.githubusercontent.com/23313203/93346888-beb8ee80-f834-11ea-9642-9619964863e0.png)

2020-09-17 07:19 UTC, JonatanPaalsson approved these changes

2020-09-17 07:24 UTC, JonatanPaalsson commented
LGTM! Really great job with everything and supernice with some more tests 👍 Regarding the issue of missing info I think that it should be filed as a seperate issue 😄

2020-09-17 07:58 UTC, marasva commented
I skissene står det "kundeinfo", men i prod står det "min profil". Har ikke fått sjekket hva det skal være med Malin enda!

2020-09-17 11:40 UTC, lobunto approved these changes

2020-09-17 11:43 UTC, merged