OMEGA-89: New layout for Min Side
3lvia/kunde-elvia-web pull request #26
Opened 2020-09-03 15:01 UTC by eTallang

OMEGA-89

## What is the reason for this change?
A new layout is needed for the new version of min side.

### What is the expected result?
The implementation should look like the designs in [Figma](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=9560%3A55962).

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] The implementation complies with the designs in Figma.
- [ ] URL's in the breadcrumbs and tabs makes sense
- [ ] Active tab is always visible and correct, even when navigating through the URL
- [ ] Should the tabs be made into a new component? If so, where and called what (reminding that it already exists a Tab component in hdd-react).
- [ ] All elements are accessible via keyboard.

2020-09-03 15:01 UTC, eTallang commented
**NOTE: ** Merge after [OMEGA-27](https://github.com/3lvia/kunde-elvia-web/pull/5), since this PR contains code from that branch.

2020-09-04 06:24 UTC, lobunto commented on packages/web/src/pages/minside.tsx
>          <PrivateRoute path="/minside/hanport/:contractId" component={HANPort} />
We should probably find out if we want to use norwegian or english in the url

2020-09-04 06:38 UTC, lobunto requested changes

2020-09-04 06:38 UTC, lobunto commented on packages/web/src/templates/CustomerDetail/CustomerDetail.module.scss
> +.tab {
I think the tabs, according to the design, have some padding (8px/`spaceCalc(1)`) on the sides..?

2020-09-04 06:38 UTC, lobunto commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +  ]
As mentioned about the language above, we need some consistency for the urls. Above we have `/minside/hanport` here we have `/han-port`. Maybe we should use what is defined in the `basePaths.json`?

2020-09-04 06:38 UTC, lobunto commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +        })}
```suggestion
        {breadcrumbs.map((breadcrumb, index) => (
            <Link to={breadcrumb.url} key={index}>
              {breadcrumb.name}
            </Link>
          )
        )}
```

2020-09-04 06:38 UTC, lobunto commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.module.scss
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
Is this going to repeat for several rows? Then it could be written `grid-template-columns: repeat(4, 1fr)`

2020-09-04 06:38 UTC, lobunto commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.module.scss
> +    grid-template-columns: 1fr 1fr 1fr;
Same here as above (if that is the case)

2020-09-04 07:04 UTC, eTallang commented on packages/web/src/templates/CustomerDetail/CustomerDetail.module.scss
> +.tab {
Good catch!

2020-09-04 07:05 UTC, eTallang commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.module.scss
> +    grid-template-columns: 1fr 1fr 1fr 1fr;
Should be fixed through [OMEGA-27](https://github.com/3lvia/kunde-elvia-web/pull/5)

2020-09-04 07:06 UTC, eTallang commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.module.scss
> +    grid-template-columns: 1fr 1fr 1fr;
Should be fixed through [OMEGA-27](https://github.com/3lvia/kunde-elvia-web/pull/5)

2020-09-04 09:51 UTC, eTallang commented on packages/web/src/pages/minside.tsx
>          <PrivateRoute path="/minside/hanport/:contractId" component={HANPort} />
I guess we landed on Norwegian. Do you think we should do any further changes to this PR then?

2020-09-04 10:31 UTC, lobunto commented on packages/web/src/pages/minside.tsx
>          <PrivateRoute path="/minside/hanport/:contractId" component={HANPort} />
Seems so. Then we need to add some redirects as well, because customers may have SMS's containing especially links to `/minside/accessrequest`, maybe this could redirect to `/minside/tilgangstyring`.

2020-09-07 11:56 UTC, lobunto requested changes
Routes for `/minside/invoices` should also be renamed to norwegian.

2020-09-10 06:38 UTC, lobunto approved these changes

2020-09-10 10:59 UTC, merged