fix(web): adds support for preview to templates
3lvia/kunde-elvia-web pull request #3
Opened 2020-08-31 14:52 UTC by t0ff3r

OMEGA-X

## What is the reason for this change?
Titles use incorrect font styles.  

[Example screenshot of the problem if possible]

### What is the expected result?
Titles should look the same as in the Figma typography sketches.

[Url or screenshot if possible]

## How is it solved?
Adds correct font styles and changed all titles to use header tags.  

[Example screenshot of the solution if possible]

## Any changes/updates that may affect others?
|                                     |Changed|
|-------------------------------------|-------|
| Unit tests                          |   x   |
| Dependencies                        |       |
| Environment variables               |       |
| Build scripts                       |       |

## How can it be tested and verified?

- [ ] Titles are using header tags.
- [ ] Titles looks identical with the typography defined in Figma.
- [ ] Titles in `/min-side` should not be affected and continue to look like this: [screenshot]
- [ ] Unit tests named `typography/titles`

2020-09-01 10:07 UTC, OysteinThuen commented
Build #3037 successfully built and deployed.

- Prod: https://5f4e1ccf49ba2ff981857437--elvia-prod.netlify.app
- Test: https://5f4e1c85fd2dd0e5fe2402a0--elvia-test.netlify.app

2020-09-02 08:55 UTC, JonatanPaalsson requested changes

2020-09-02 08:55 UTC, JonatanPaalsson commented on packages/web/gatsby-node.js
> +  const transformer = createTransformer({
You could get these values from `config/contentful.ts`. Up to you 😄

2020-09-02 08:55 UTC, JonatanPaalsson commented on packages/web/contentful/fetch.js
> +  let options = {
Why let and not const?

2020-09-02 08:59 UTC, JonatanPaalsson commented
I only get redirected to the frontpage when following the steps in How it can be tested and verified 😕

2020-09-02 09:49 UTC, t0ff3r commented
> I only get redirected to the frontpage when following the steps in How it can be tested and verified 😕

Just realised the same thing. Looking into it

2020-09-02 11:00 UTC, t0ff3r commented on packages/web/gatsby-node.js
> +  const transformer = createTransformer({
I know but this part is about to be broken out to its own package. @FredricW will use the correct config when he sets it up the new way

2020-09-02 11:02 UTC, FredricW commented on packages/web/contentful/fetch.js
> +  let options = {
let it be



;)

2020-09-02 11:42 UTC, JonatanPaalsson approved these changes

2020-09-02 12:31 UTC, JonatanPaalsson requested changes
Mangler fallback om ID ikke finnes

2020-09-03 08:48 UTC, FredricW commented
To ting: Er det ikke litt forvirrende å bli tatt til forsiden hvis id ikke finnes? Jeg trodde jeg hadde skrevet feil url flere ganger.
Men hvis det likevel er ønskelig, skal det også være fallback på `/preview` (som for øyeblikket er hvit)?

Hadde det vært enklere å forstå om den sa at id ikke finnes?

2020-09-03 08:58 UTC, FredricW approved these changes
LGTM. Kan eventuelt fikse fallback greiene i en senere pr

2020-09-03 09:00 UTC, FredricW commented on packages/web/contentful/fetch.js
> +    options = {
Isn't mutating existing variables like this kind of an antipattern?

2020-09-03 09:02 UTC, FredricW commented on packages/web/contentful/fetch.js
> +    options = {
I mean, it is not straight forward to know what the options object will look like when all of this goes through

2020-09-03 11:23 UTC, merged