Feature/omega 27 customer relation overview page
3lvia/kunde-elvia-web pull request #5
Opened 2020-09-01 06:24 UTC by ragnhildlarsen

OMEGA-27

## What is the reason for this change?
Customers that have multiple customer relations need an overview page for all their customer relations.  

### What is the expected result?
Customers with multiple customer relations should se an overview page if going to /minside/kundeforhold. Customers with only one customer relation should be redirected to the only customer relation they have /minside/kundeforhold/customerId. Customers with no customer relations should be redirected to access request page /minside/accessrequest. When you click on a custom relation card on the overview page you should be navigated to a detail page with an url /minside/kundeforhold/customerId which currently only shows "test".

[Figma sketches](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=9334%3A57402)

## How is it solved?
A new template is created for CustomerRelationOverview. This component accesses the customer store and uses that data to decide what should be shown or if the customer should be redirected. 
A dummy template for CustomerDetail have been created to be a placeholder for the detail page for a Customer Relation (this might be excessive if someone else is working on the actual page). 

## Any changes/updates that may affect others?
|                                     |Changed|
|-------------------------------------|-------|
| Unit tests                          |      |
| Dependencies                        |       |
| Environment variables               |       |
| Build scripts                       |       |

## How can it be tested and verified?

- [ ] Test behaviour for different test customers and check that the correct data is shown.
- [ ] UI looks and behaves identical to design defined in Figma.
- [ ] enter /minside/kundeforhold in the url to navigate to the page

2020-09-01 07:25 UTC, OysteinThuen commented
Build #3007 successfully built and deployed.

- Prod: https://5f4df6a849ba2fc64d8572c3--elvia-prod.netlify.app
- Test: https://5f4df69ef0854f9e7f72d17f--elvia-test.netlify.app

2020-09-01 08:21 UTC, OysteinThuen commented
Build #3012 successfully built and deployed.

- Prod: https://5f4e03f949ba2fd8908573f9--elvia-prod.netlify.app
- Test: https://5f4e043890bc06a8916cb5ba--elvia-test.netlify.app

2020-09-01 09:49 UTC, eTallang commented on packages/web/src/components/CustomerCard/CustomerCard.module.scss
> +  box-shadow: 0px 0px 40px rgba(0, 0, 0, 0.03);
I believe this shadow color exists as a variable in theme.

2020-09-01 09:49 UTC, eTallang commented on packages/web/src/components/CustomerCard/CustomerCard.module.scss
> +  background-color: white;
So does the white color `map-get($colors, 'white')`

2020-09-01 09:51 UTC, eTallang commented on packages/web/src/components/CustomerCard/CustomerCard.tsx
> +export const CustomerCard = ({ customer }: CustomerCardProps) => {
To get typings for a functional react component, you can define the type like this:
```
export const CustomerCard: React.FC<CustomerCardProps> = ({customer}) = {
```

2020-09-01 11:31 UTC, eTallang commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +  const customerRelations = useSelector(customersSelectors.getAllCustomers)
Could we use some types on the `useSelector`-method to improve type safety?

2020-09-01 11:34 UTC, OysteinThuen commented
Build #3065 successfully built and deployed.

- Prod: https://5f4e313311d0c4dc7846480c--elvia-prod.netlify.app
- Test: https://5f4e31169d1fbe00a859a83d--elvia-test.netlify.app

2020-09-01 11:51 UTC, ragnhildlarsen commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +  const customerRelations = useSelector(customersSelectors.getAllCustomers)
Do you mean in this file or in the selectors file for customersSelectors? I see that some of the other selectors have type so I can add it in the selectors file like this:
`export const getAllCustomers = (state: RootState): Record<string, Customer> =>
  state.customers.customersById`

2020-09-01 12:10 UTC, OysteinThuen commented
Build #3082 successfully built and deployed.

- Prod: https://5f4e39e56bfe1500c6cd8728--elvia-prod.netlify.app
- Test: https://5f4e39cd6bfe150127cd85c1--elvia-test.netlify.app

2020-09-03 15:04 UTC, JonatanPaalsson requested changes
Får ikke testet dette i test-miljö, kanske vi mangler node_env der? 🤔

2020-09-04 06:54 UTC, ragnhildlarsen commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +  switch (Object.keys(customerRelations).length) {
I don't think it is necessary to factor in `privateCustomerRelations` in the switch, as the main goal of the switch is to separate between the different scenarios where you have 0, 1 or multiple customer relations. The separation between private and organisation customer relations is taken into account in the default case in the switch.

2020-09-04 08:34 UTC, ragnhildlarsen commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +    <>{props.children}</>
I don' know. When I remove the `<>` and `</>` that wraps the props I get an error. Do you have a suggestion to how I can do it differently?

2020-09-04 09:25 UTC, JonatanPaalsson commented on packages/web/src/templates/CustomerRelationOverview/CustomerRelationOverview.tsx
> +  switch (Object.keys(customerRelations).length) {
Ah right, now I understand! I think `allCustomerRelations` would be a better name for `customerRelations`, but that is just preference 👍

2020-09-04 12:51 UTC, JonatanPaalsson approved these changes

2020-09-04 13:04 UTC, merged