fix: removes deps from web and adds contentful to contentful package
3lvia/kunde-elvia-web pull request #51
Opened 2020-09-08 11:46 UTC by t0ff3r

## What is the reason for this change?

Clean up some dependencies in web

### What is the expected result?

Web should not install packages not in use

## How is it solved?

Removed gatsby-source-contentful, contentful-management, contentful and prop-types. Added contentful to contentful-source package

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |     x    |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Hopefully everything builds as normal

2020-09-09 06:55 UTC, JonatanPaalsson requested changes

2020-09-09 06:55 UTC, JonatanPaalsson commented on packages/web/package.json
> -    "prop-types": "^15.7.2",
We are using prop-types in some components in hdd-react, should we then move this dependency to hdd-react? Bit unsure how this actually works

2020-09-09 06:55 UTC, JonatanPaalsson commented on packages/web/package.json
> -    "gatsby-plugin-sass": "^2.3.2",
we don't need this? 🤯

2020-09-09 12:44 UTC, t0ff3r commented on packages/web/package.json
> -    "prop-types": "^15.7.2",
Yes - lets move it.

2020-09-11 12:45 UTC, JonatanPaalsson approved these changes

2020-09-11 13:27 UTC, merged