Refactor/omega 54 move poweroutage map to main category
3lvia/kunde-elvia-web pull request #6
Opened 2020-09-01 06:37 UTC by lobunto

OMEGA-54

## What is the reason for this change?
This refactoring mostly solves some design issues (and redirect) when we are going to implement the power outage map into the Main Category page.

TODO (but can be done after the PR has been merged):
Update URL for private and pro menus with Alias to "strømbrudd" Main Category in Contentful

### What is the expected result?
The power outage map should be available at `/strombruddskart`
The `/kart` path should redirect to `/strombruddskart`

Test url: `/strombruddskart`

[Url or screenshot if possible]

## How is it solved?
Add redirect from /kart to "strømbrudd" Main Category
Remove title and preamble for the power outage map component
Minor style fixes: scrolling, dynamic height

## Any changes/updates that may affect others?
|                                     |Changed|
|-------------------------------------|-------|
| Unit tests                          |     |
| Dependencies                        |       |
| Environment variables               |       |
| Build scripts                       |       |

## How can it be tested and verified?

- [ ] The power outage map should be available at `/strombruddskart`
- [ ] You are able to integrate with the power outage map
- [ ] The power outage map should scale to full width on mobile devices

![Screenshot 2020-09-01 at 08 34 47](https://user-images.githubusercontent.com/6702553/91810342-008b4780-ec2e-11ea-9175-c675e2704f66.png)

2020-09-01 07:00 UTC, OysteinThuen commented
Build #2999 successfully built and deployed.

- Prod: https://5f4df0a249ba2fc59a856e6d--elvia-prod.netlify.app
- Test: https://5f4df0a011d0c492d84649ea--elvia-test.netlify.app

2020-09-01 11:10 UTC, FredricW commented on packages/hdd-react/src/components/PowerOutageMap/PowerOutageMap.module.scss
> +    height: 400px;
```suggestion
    height: emCalc(400px);
```

2020-09-01 11:10 UTC, FredricW commented on packages/hdd-react/src/components/PowerOutageMap/PowerOutageMap.module.scss
>      height: 800px;
```suggestion
    height: emCalc(800px);
```

2020-09-01 11:10 UTC, FredricW commented on packages/web/src/templates/Article/Article.module.scss
> +    & > p > a {
This means only the first level of a tags will get these styles. Is that what we want?

2020-09-01 12:00 UTC, OysteinThuen commented
Build #3078 successfully built and deployed.

- Prod: https://5f4e36e976c3d80096b8a983--elvia-prod.netlify.app
- Test: https://5f4e36e442be2e00b3faff59--elvia-test.netlify.app

2020-09-01 12:42 UTC, OysteinThuen commented
Build #3094 successfully built and deployed.

- Prod: https://5f4e4182f747cc0949647daa--elvia-prod.netlify.app
- Test: https://5f4e415352fcbe086be9eac3--elvia-test.netlify.app

2020-09-02 06:14 UTC, lobunto commented on packages/web/src/templates/Article/Article.module.scss
> +    & > p > a {
Fixed it to what that was intentional. All links in paragraphs should have this style, not only the first level.

2020-09-02 06:35 UTC, FredricW approved these changes

2020-09-02 06:49 UTC, FredricW requested changes
Set width 100% and height 100vh and we are good :)

2020-09-02 06:53 UTC, lobunto commented
> Set width 100% and height 100vh and we are good :)

Where? 🤔

2020-09-02 06:54 UTC, FredricW commented
On the map :)

2020-09-02 07:51 UTC, FredricW approved these changes

2020-09-02 08:10 UTC, merged