feature(emptyInvoice): add emptyInvoiceBox component
3lvia/kunde-elvia-web pull request #60
Opened 2020-09-10 13:49 UTC by marasva

[OMEGA-99](https://elvia.atlassian.net/browse/OMEGA-99?atlOrigin=eyJpIjoiMTJmMTgwYWE4ODc0NDMxYzkwNTUwNWY2ZjVkOWJjM2QiLCJwIjoiaiJ9)

## What is the reason for this change?

Customers that has not yet received an invoice is shown an empty table. 
![image](https://user-images.githubusercontent.com/23313203/92738208-0abeeb80-f37c-11ea-809c-6e13e824a659.png)

### What is the expected result?
A new view with text and icons explaining that the customer have not yet received an invoice.

![image](https://user-images.githubusercontent.com/23313203/92738287-1ad6cb00-f37c-11ea-961b-55add727301c.png)

## How is it solved?

Add new Begrep in contentful and add a new component with icons from Figma.

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Use the test user Per Hansen and go into his meterpoint view for Ole Nilsens gate 21 (222222222)
- [ ] A new view will show with the same design as above
- [ ] Looks as usual (with a table view of invoices) if you try some of the other meterpoints.

2020-09-10 14:07 UTC, marasva commented
I changed the @ media to 1120px because I could not find a way to keep the design without breaking it at the breakpoint between 1024px - 1060px through using the regular max-width for MobileAndTablet.

2020-09-11 10:52 UTC, eTallang commented on packages/hdd-react/src/components/EmptyInvoiceBox/EmptyInvoiceBox.tsx
> +          <div>
Are these `<div>` elements that wrap the icons necessary? :slightly_smiling_face: Maybe we could do something like:
```
<HddSendEmailLargeColor />
<HddSendEmailSmallColor className={css.sendEmailLeft2} />
<HddPaperPlaneOrangeSmallColor className={css.paperPlaneLeft} />
```

2020-09-14 11:13 UTC, marasva commented on packages/hdd-react/src/components/EmptyInvoiceBox/EmptyInvoiceBox.tsx
> +          <div>
I cannot manage to make it work without them, but I agree that it looks unnecessary

2020-09-17 07:16 UTC, JonatanPaalsson requested changes

2020-09-17 07:16 UTC, JonatanPaalsson commented on packages/ui/src/components/EmptyInvoiceBox/EmptyInvoiceBox.tsx
> +      <div className={classes} style={style}>
Is it possible to remove some of these divs? Some icons are just wrapped in a empty div and maybe the classnames can go directly on the icons?

2020-09-21 06:45 UTC, lobunto commented
@marasva what is the status for this PR?

2020-09-21 10:13 UTC, marasva commented
Well, I do not know of any "smoother" way to implement the svgs without so many divs, so for me it is finished. Do not think @JonatanPaalsson have looked further on it either?

2020-09-22 18:35 UTC, t0ff3r commented
Seems overly complex to import and place every icon freely one by one. I am no expert on svgs but could we solve this by making a nested svg instead of handling each of them separately? 

This article seems interesting: https://www.sarasoueidan.com/blog/mimic-relative-positioning-in-svg/

2020-09-23 06:35 UTC, marasva commented
> 
> 
> Seems overly complex to import and place every icon freely one by one. I am no expert on svgs but could we solve this by making a nested svg instead of handling each of them separately?
> 
> This article seems interesting: https://www.sarasoueidan.com/blog/mimic-relative-positioning-in-svg/

Will look into the article you sent.

2020-09-24 12:04 UTC, JonatanPaalsson approved these changes
LGTM!

2020-09-25 11:24 UTC, merged