Fix table style
3lvia/kunde-elvia-web pull request #72
Opened 2020-09-14 12:14 UTC by steinmy

Some fixes to the style of the table component
Note: The css in the table component stylesheet did not pass the style linter. This was due to code already present, not due to the changes introduced in this pull request. After discussion with other frontenders, I have disabled the style-lint rule "no-descending-specificity". Feel free to comment if you disagree.

OMEGA-138

## What is the reason for this change?

Table component is not as it should according to sketcehs
- No borders between rows on mobile view
- On mobile view the first row is only left aligned when containing a `<p>` inside a `<div>`
- Header has too low height
- The first column expands to take all extra horizontal space, instead of distributing between columns

![image](https://user-images.githubusercontent.com/20183313/93083080-4e726780-f692-11ea-8e8f-0291535511f5.png)
![image](https://user-images.githubusercontent.com/20183313/93083094-5500df00-f692-11ea-9c3c-406dbd42630d.png)

### What is the expected result?

Tables should look the same as in the Figma sketches.

https://www.figma.com/file/gh5MaG2NWKVODTk1p3cO6s/Tables?node-id=3%3A292

## How is it solved?

Changed stylesheet of table component

![image](https://user-images.githubusercontent.com/20183313/93083019-326ec600-f692-11ea-86b2-3b5b19ec4cbe.png)
![image](https://user-images.githubusercontent.com/20183313/93083034-38fd3d80-f692-11ea-959b-77fb22a97d47.png)

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |        |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Tables at for example /mitt-elvia/prisoversikt look like the screenshots under "How is it solved?" above

2020-09-14 13:39 UTC, eTallang requested changes

2020-09-14 13:39 UTC, eTallang commented on .stylelintrc.js
> +    'no-descending-specificity': null,
How come we have disabled this lint-rule? :slightly_smiling_face:

2020-09-14 13:39 UTC, eTallang commented on packages/hdd-react/src/components/Table/Table.module.scss
> +    }
Maybe we could concat this with the CSS on line 87?

```
...
  &:first-child,
  &:first-child div p {
    text-align: left;
  }
```

Or maybe your contribution even solves both scenarios, and the rule on line 87 can be removed entirely?

2020-09-15 07:19 UTC, steinmy commented on .stylelintrc.js
> +    'no-descending-specificity': null,
Let's discuss this in person :)

2020-09-15 07:21 UTC, steinmy commented on packages/hdd-react/src/components/Table/Table.module.scss
> +    }
I tried removing line 87 to see if this new code is enough, but it didn't seem to work, as the `<p>` has an inline style telling it to align to the right. I'm not sure where this comes from, probably from Contentful somehow?

2020-09-15 09:13 UTC, eTallang approved these changes

2020-09-15 09:55 UTC, merged