Feat/omega 146 meteringpoint table filter
3lvia/kunde-elvia-web pull request #90
Opened 2020-09-16 09:46 UTC by eTallang

OMEGA-146

## What is the reason for this change?

Previously, there was no way to filter the list of metering points in the metering points table. This is a desired functionality, especially for clients with many metering points.

### What is the expected result?

The metering points table should now have a filter above.

[Url or screenshot if possible]
![image](https://user-images.githubusercontent.com/24789715/93314541-2f96e100-f80a-11ea-96cb-baea0ad7d26d.png)

## How can it be tested and verified?

- [ ] Check that the implementation matches the design in [Figma](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=10181%3A67879)
- [ ] Check that the input can filter the list on all specified props (metering point no, address and metering point id)
- [ ] Check that the implementation follows best practices
- [ ] Check that the implementation is responsive
- [ ] Check that the implementation is performant.

2020-09-16 18:28 UTC, t0ff3r commented on packages/web/src/templates/Meterpoints/MeteringPoints.tsx
> +              <th className={css.actionColumn}></th>
Shouldn't this be terms from contentful?

2020-09-17 06:35 UTC, lobunto commented
@eTallang do you know of that we do have a useSearch hook? Could we probably consider using that here as well..

2020-09-17 06:48 UTC, ragnhildlarsen commented on packages/web/src/templates/Meterpoints/Meterpoints.module.scss
> +}
Looks like the search/filter icon should have more padding-right (16px/24px) on desktop (it's a bit unclear in the sketches so maybe double check with designer).

2020-09-17 06:50 UTC, ragnhildlarsen commented
Should there be any empty state when a search give no result. Maybe outside the scope of this task but I was just thinking about it :) 
<img width="1680" alt="Screenshot 2020-09-17 at 08 48 29" src="https://user-images.githubusercontent.com/50363113/93430344-d6d74f00-f8c2-11ea-9714-15639ec9c39c.png">

2020-09-21 06:40 UTC, lobunto commented
@eTallang are you following up the comments here..? :)

2020-09-21 06:55 UTC, eTallang commented on packages/web/src/templates/Meterpoints/Meterpoints.module.scss
> +}
Yes I noticed this during development, however input-field is a component with a icon-prop, so I wanted to stay consistent with the other places we use icons in a text field. I'll check this with designer.

2020-09-23 08:00 UTC, ragnhildlarsen commented on packages/web/src/templates/Meterpoints/MeteringPoints.tsx
> +        'meteringPoint.address.letter',
Should it be possible to search on zipCode?

2020-09-23 08:08 UTC, ragnhildlarsen commented
Looks like placeholder text should be truncated on mobile: [https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=9755%3A61892](https://www.figma.com/file/sJHoScmQRq0hlr6AcHI9WB/Elvia.no?node-id=9755%3A61892)
<img width="393" alt="Screenshot 2020-09-23 at 10 05 40" src="https://user-images.githubusercontent.com/50363113/93984723-7776b480-fd84-11ea-8642-b612b5febafc.png">

2020-09-23 08:21 UTC, ragnhildlarsen requested changes
Looks good! Just had a few comments about placeholder text on mobile and being able to search on zip code. Code looks good to me.

2020-09-25 06:31 UTC, ragnhildlarsen approved these changes
Looks good to me :)

2020-09-25 08:01 UTC, lobunto commented
Should the search field be visible for even users with a single contract? A suggestion is to show it for those with 5 or more ...

2020-09-25 08:28 UTC, eTallang commented
> Should the search field be visible for even users with a single contract? A suggestion is to show it for those with 5 or more ...

I think the plan is that when you have few contracts, you won't see the table at all (replace the tab with a tab to see a single meters consumption). But maybe we should confirm this with design.

2020-09-25 12:46 UTC, eTallang commented
We've decided to hide the filter until the task for replacing the table with the metering point page has been completed. This is because the filter does not serve any purpose for most of Elvias customers, since the majority only have one metering point.
This PR does not use the new flag-feature, but uses a poor-mans flag (a `if (false)` statement). @t0ff3r would you still take a look to get this PR ready for merge?

2020-09-25 13:02 UTC, lobunto approved these changes

2020-09-25 13:04 UTC, lobunto requested changes

2020-09-25 13:04 UTC, lobunto commented on packages/ui/src/components/FormInputs/FormInputs.module.scss
> +  text-overflow: ellipsis;
Discovered just now that this makes the prefix input hide the +47.. :p 

<img width="726" alt="Screenshot 2020-09-25 at 15 03 46" src="https://user-images.githubusercontent.com/6702553/94270440-52c73c00-ff40-11ea-8e83-69f8a42c5f35.png">

2020-09-25 13:04 UTC, lobunto commented on packages/ui/src/components/FormInputs/FormInputs.module.scss
> +  text-overflow: ellipsis;
So it will probably also affect every form that uses the phonenumber component

2020-09-28 07:39 UTC, eTallang commented on packages/ui/src/components/FormInputs/FormInputs.module.scss
> +  text-overflow: ellipsis;
Absolutely. A terrifying side effect I should have anticipated. We will have to target the inputs that only have a placeholder.

2020-09-28 08:03 UTC, eTallang commented on packages/ui/src/components/FormInputs/FormInputs.module.scss
> +  text-overflow: ellipsis;
I've fixed it by slightly increasing the width of the input.

2020-09-28 09:13 UTC, t0ff3r commented on packages/web/src/hooks/useSearch.tsx
> +            (dataItem as any).locale === null
why are we casting this to any?

2020-09-28 10:24 UTC, eTallang commented on packages/web/src/hooks/useSearch.tsx
> +            (dataItem as any).locale === null
A cast to `any` is "necessary", since `dataItem` is of type `T`. A better type cast would be to say`dataItem as SearchDataItem`, however type T and SearchDataItem has no overlap, so the IDE complains. To fix this, I could convert it to `unknown` first, but then it turns out to be a very long line of code.

Considering that the `SearchDataItem` is an interface that doesn't provide any big typing support, a cast to `any` made sense to me instead of going with the first approach.

2020-09-28 10:39 UTC, t0ff3r commented on packages/web/src/templates/Meterpoints/MeteringPoints.tsx
> +      {false && (
false && ??

2020-09-28 10:40 UTC, t0ff3r approved these changes

2020-09-28 10:41 UTC, merged