Testing OMEGA-110 tab view on mobile
3lvia/kunde-elvia-web pull request #95
Opened 2020-09-16 14:04 UTC by marasva

OMEGA-X
This is just a test
## What is the reason for this change?

Titles use incorrect font styles.

[Example screenshot of the problem if possible]

### What is the expected result?

Titles should look the same as in the Figma typography sketches.

[Url or screenshot if possible]

## How is it solved?

Adds correct font styles and changed all titles to use header tags.

[Example screenshot of the solution if possible]

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            | x       |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

- [ ] Titles are using header tags.
- [ ] Titles looks identical with the typography defined in Figma.
- [ ] Titles in `/min-side` should not be affected and continue to look like this: [screenshot]
- [ ] Unit tests named `typography/titles`

2020-09-17 08:24 UTC, ragnhildlarsen commented
Looks like the arrows are not center aligned with the text in the tabs
![IMG_1529](https://user-images.githubusercontent.com/50363113/93440596-d2fdf980-f8cf-11ea-85d1-e3d4b5be6413.PNG)

2020-09-17 08:28 UTC, ragnhildlarsen commented
The ripple effect looks a bit oval. Should it be a round circle?
![RPReplay_Final1600330863](https://user-images.githubusercontent.com/50363113/93442458-4f90d800-f8d0-11ea-9214-2cdde3f17b6c.gif)

2020-09-21 11:23 UTC, marasva commented
The extra items in the LinkItem array will be removed eventually but are added for now to make it possible to see the tabs.

2020-09-22 13:25 UTC, t0ff3r requested changes

2020-09-22 13:25 UTC, t0ff3r commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +  }
You should probably use requestAnimationFrame here instead of setInterval. Or at least before setInterval (fallback). We have already done something like this in scroll.ts

2020-09-22 13:25 UTC, t0ff3r commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +      if (scrollLeft < 16) {
What is this number 16? Could maybe be set in a constant?

2020-09-22 13:25 UTC, t0ff3r commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +            <span>&gt;</span>
Do we have an icon for this?

2020-09-22 13:26 UTC, t0ff3r commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +      containerRef.current?.offsetWidth < containerRef!.current.scrollWidth
What is the exclamation point in containerRef here?

2020-09-22 13:27 UTC, t0ff3r commented on packages/web/src/templates/CustomerDetail/CustomerDetail.module.scss
> +  padding: 0 spaceCalc(1); /* explicitly setting it here for iOS */
How is this explicitly set for ios?

2020-09-22 13:27 UTC, t0ff3r commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +            <span>&lt;</span>
Icon?

2020-09-22 13:39 UTC, marasva commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +      if (scrollLeft < 16) {
ah yes, it's the pixel count of the scroll. Can set it as a constant.

2020-09-22 13:40 UTC, marasva commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +            <span>&gt;</span>
Yes, but the size of the icons then get too small and behave differently since they are SVGs, but can try to look at it again.

2020-09-22 13:43 UTC, marasva commented on packages/web/src/templates/CustomerDetail/CustomerDetail.module.scss
> +  padding: 0 spaceCalc(1); /* explicitly setting it here for iOS */
For some reason, on iPhone at least, the standard padding gets doubled. The standard padding for a button is 8px which it is on Android and what not, but on iPhone (maybe not specifically iOS) the padding gets doubled on both sides. I don't know what causes this

2020-09-24 09:18 UTC, marasva commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +  }
I tried using requestAnimationFrame now, but don't know if I implemented it correctly?

2020-09-28 10:43 UTC, t0ff3r commented
@marasva whats the next steps for this PR?

2020-09-30 10:38 UTC, t0ff3r commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +    },
I guess this should not go out with this pr?

2020-09-30 10:43 UTC, marasva commented on packages/web/src/templates/CustomerDetail/CustomerDetail.tsx
> +    },
Yes, it's only for "demonstration" purposes

2020-09-30 11:42 UTC, FredricW requested changes

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.module.scss
> +  margin-bottom: spaceCalc(9.5);
Er 9.5 riktig her? Hvis du ender med noe annet enn et heltall i spaceCalc så følger vi ikke lenger spacing standarden vi har blitt enige om

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.module.scss
> +    background-color: #efefef;
`map-get($colors, 'someColor')`

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.module.scss
> +    font-size: 14px;
Her skal det vel brukes en spesifikk font?

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +  const [width, setWidth] = React.useState(window.innerWidth)
Er det global størrelse på window som bestemmer om tabs skal være scrollbare, eller størrelsen på tab-containeren?

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +  const [width, setWidth] = React.useState(window.innerWidth)
Vi har også en hook som gjør dette for spesifikke elementer. Se `useElementHeightAndWidth`

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +  useWindowDimensions()
Denne kalles, men return verdien taes ikke i mot?

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +      : false
```suggestion
      containerRef.current?.offsetWidth < containerRef.current?.scrollWidth
```
Å returnere `true` hvis en expression blir `true` og vice versa er det samme som å bare returnere en expression.

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +      direction == 'left'
```suggestion
      direction === 'left'
```
Alltid bruk trippel lik :)

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +    return containerRef.current != null &&
```suggestion
    return containerRef.current !== null &&
```
trippel lik (eller trippel "ikke lik")

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +        {hasOffset() ? (
Foretrekker å gjøre slike funksjonskall utenfor template og heller lagre det i en (boolean)variabel som brukes i template. Spesielt hvis verdien som funksjonen trenger skal brukes flere steder, sånn som her.
I dette tilfellet bør du også bruke `&&` fremfor `?` så slipper du å returnere noe dersom `hasOffset` er `false`.

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +          {tabs !== null && tabs !== undefined ? (
Kan tabs være både null og undefined? Eller holder det med å sette en default verdi og sjekke kun den ene?

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +          {tabs !== null && tabs !== undefined ? (
det er også mulig å bare gjøre optional chaining før map og fjerne hele sjekken.
```jsx
tabs?.map(...)
```

2020-09-30 11:42 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +        {hasOffset() ? (
Samme som tidligere

2020-09-30 11:42 UTC, FredricW commented on packages/web/tsconfig.json
> +  "include": ["./src", "../ui/src/components/Tabs"],
Hva skjer her egentlig?

2020-09-30 11:46 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.module.scss
> +    background: #efefef
`map-get($colors, 'someColor')`

2020-09-30 11:48 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +export const Tabs: React.FC<TabsProps> = ({ tabs, uri }) => {
```suggestion
export const Tabs: React.FC<TabsProps> = ({ tabs = [], uri }) => {
```
Siden tabs er optional kan det være greit å sette en default verdi så slipper man null/undefined sjekker etterpå

2020-09-30 11:49 UTC, marasva commented on packages/ui/src/components/Tabs/Tabs.module.scss
> +  margin-bottom: spaceCalc(9.5);
Ah, dette tror jeg det er Erik som hadde lagt inn orginalt, jeg bare bytta plass på dem. Men skal vel ikke være noe problem å bruke et heltall i stedet for.

2020-09-30 11:51 UTC, marasva commented on packages/web/tsconfig.json
> +  "include": ["./src", "../ui/src/components/Tabs"],
Det vet jeg ikke. Skulle sikkert ikke ha comitta tsconfig?

2020-09-30 11:53 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +  const [arrow, setHideArrows] = useState<string>()
Her sier du at arrow alltid vil være av typen string, men du setter ingen default string verdi så den vil være null eller undefined ut av boksen.

```suggestion
  const [arrow, setHideArrows] = useState<string>('')
```

2020-09-30 11:54 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +  const [arrow, setHideArrows] = useState<string>()
Dette burde vært catchet av es-lint så hvis du ikke får feil i vscode eller under commit så er det noe som ikke stemmer helt.

2020-09-30 11:57 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.tsx
> +                getProps={({ isPartiallyCurrent }) => {
Hva betyr `isPartiallyCurrent`?

2020-09-30 12:03 UTC, marasva commented on packages/ui/src/components/Tabs/Tabs.tsx
> +                getProps={({ isPartiallyCurrent }) => {
Det vet jeg ikke. Er fra Erik eller tidligere kode, men kan høre med ham hva det gjør.

2020-09-30 12:46 UTC, FredricW commented on packages/web/tsconfig.json
> +  "include": ["./src", "../ui/src/components/Tabs"],
Okei, så hva tenker du vi gjør med dette da? :)

2020-09-30 12:59 UTC, marasva commented on packages/ui/src/components/Tabs/Tabs.tsx
> +                getProps={({ isPartiallyCurrent }) => {
isPartiallyCurrent - true if the location.pathname starts with the anchor’s href. Så det kommer fra Link i gatsby :)

2020-09-30 13:19 UTC, marasva commented on packages/ui/src/components/Tabs/Tabs.module.scss
> +    font-size: 14px;
Dette er også fra Erik, men tror det bare er et "pseudo-element" så det er bare for å få spacing og ikke faktisk vises, så vet ikke hvor viktig det er med riktig font

2020-09-30 13:25 UTC, marasva commented on packages/web/tsconfig.json
> +  "include": ["./src", "../ui/src/components/Tabs"],
Fjerne det?

2020-09-30 13:27 UTC, marasva commented on packages/ui/src/components/Tabs/Tabs.tsx
> +  const [arrow, setHideArrows] = useState<string>()
Har ikke fått noen feil nei.

2020-10-01 07:37 UTC, t0ff3r commented
@FredricW re-review?

@marasva I think its better to use the commit message to tell what is changed instead of `changes after QA`

2020-10-01 08:41 UTC, FredricW commented on packages/ui/src/components/Tabs/Tabs.module.scss
> +    font-size: 14px;
snakket med Erik, du kan fjerne hele &:before blokken (og kommentaren over)

2020-10-01 08:57 UTC, FredricW commented
Lagt inn en siste kommentar! Får du ordnet opp i den så tenker jeg det er greit :) Skjønte at ikke all koden var skrevet av deg, men det er fint å få ryddet litt opp i det uansett når man er borti det. Bra jobba Marie :) 👍

2020-10-01 13:04 UTC, t0ff3r approved these changes

2020-10-01 13:05 UTC, merged