Feature/OMEGA-117 poweroutage pin component
3lvia/kunde-elvia-web pull request #99
Opened 2020-09-17 08:32 UTC by erlbe

OMEGA-X

## What is the reason for this change?

Use pins with scaling size to display power outages in map.

### What is the expected result?

A pin which scales according to number of affected customers.

## How is it solved?

Created a Pin component with accompanied style.

## Any changes/updates that may affect others?

|                       | Changed |
| --------------------- | ------- |
| Unit tests            |       |
| Dependencies          |         |
| Environment variables |         |
| Build scripts         |         |

## How can it be tested and verified?

2020-09-17 13:14 UTC, corneliusgdahling requested changes
Just some small comments, then we can :shipit: !

2020-09-17 13:14 UTC, corneliusgdahling commented on packages/poweroutage/src/components/Pin/Pin.tsx
> +        width: `${outerDiameter}px`,
use spaceCalc here?

2020-09-17 13:14 UTC, corneliusgdahling commented on packages/poweroutage/src/components/Pin/Pin.tsx
> +          width: `${innerDiameter}px`,
spaceCalc

2020-09-18 07:38 UTC, erlbe commented on packages/poweroutage/src/components/Pin/Pin.module.scss
> +      font-size: '20px';
Fixed 👍

2020-09-18 07:38 UTC, erlbe commented on packages/poweroutage/src/components/Pin/Pin.tsx
> +        </div>
Fixed 👍

2020-09-18 07:39 UTC, erlbe commented on packages/poweroutage/src/components/Pin/Pin.tsx
> +        width: `${outerDiameter}px`,
Fixed 👍

2020-09-18 07:39 UTC, erlbe commented on packages/poweroutage/src/components/Pin/Pin.tsx
> +          width: `${innerDiameter}px`,
Fixed 👍

2020-09-18 11:48 UTC, corneliusgdahling approved these changes

2020-09-18 11:56 UTC, merged